server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://192.168.1.171:3306/clientes-temporal
    username: programs
    password: 3SbaYcPuWQ9VOO82
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
  http:
    encoding:
      charset: UTF-8
      force: true
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,logfile
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url.defaultZone: http://192.168.1.171:8761/eureka/
  instance:
    hostname: 192.168.1.171
    lease-renewal-interval-in-seconds: 30
auth:
  microservice:
    url: http://192.168.1.171:8001/api/v1
user:
  microservice:
    url: http://192.168.1.171:8002/api/v1/users
administration:
  microservice:
    url: http://192.168.1.171:8003/api/v1/roles
