server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://192.168.1.241:3306/users_microservice
    username: programs
    password: 3SbaYcPuWQ9VOO82
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false   

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true  
    service-url.defaultZone: http://192.168.1.241:8761/eureka/
  instance:
    hostname: 192.168.1.241
    lease-renewal-interval-in-seconds: 30
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,logfile

jwt:
  secret: electrohogarl
administration:
  microservice:
    url: http://192.168.1.241:8003/api/v1/roles
auth:
  microservice:
    url: http://192.168.1.241:8001/api/v1